language: android
sudo: required
jdk: openjdk8
dist: trusty

env:
  global:
    - ANDROID_API=29
    - EMULATOR_API=24
    - ANDROID_BUILD_TOOLS=29.0.1
    - ADB_INSTALL_TIMEOUT=5
    - ANDROID_ABI=armeabi-v7a

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - tools
    - platform-tools
    - tools

    #android
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API

    #extras
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    #system images
    - sys-img-$ANDROID_ABI-android-$EMULATOR_API


before_install:
  - chmod +x gradlew
 # Get rid of warning
  - touch $HOME/.android/repositories.cfg
  # Accept licences
  - echo yes | sdkmanager --update > /dev/null
  - echo yes | sdkmanager --licenses > /dev/null
  # Install the rest of tools (e.g., avdmanager).
  - echo yes | sdkmanager tools > /dev/null
  # Update emulator
  - echo yes | sdkmanager 'emulator' > /dev/null
  # Install the system image.
  - echo yes | sdkmanager "platforms;android-$ANDROID_API" > /dev/null
  - echo yes | sdkmanager "system-images;android-$EMULATOR_API;default;$ANDROID_ABI" > /dev/null
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n emulatorname -k "system-images;android-$EMULATOR_API;default;$ANDROID_ABI"
  - $ANDROID_HOME/emulator/emulator -memory 1024 -avd emulatorname -skin 768x1280 -no-boot-anim -no-audio -no-window -no-snapshot -no-snapstorage -no-cache &


before_script:
  - yes | cp -rf keys.xml.example app/src/main/res/values/keys.xml
  - yes | cp -rf google-services.json.example app/google-services.json
  - echo 'org.gradle.jvmargs=-Xms4g -Xmx4g -XX:+HeapDumpOnOutOfMemoryError' >> gradle.properties
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck

#after_success:
#  - bash <(curl -s https://codecov.io/bash)